export const RoutePaths = {
  HOME: '/',
  LOGIN: '/login',
  LIBRARY: '/library',
  TASK: '/task',
  BULLET: '/bullet',
  MEDIA_FETCH: '/media-fetch',
  SOURCE: '/source',
  SETTING: '/setting',
  CONTROL: '/control',
  BGM_OAUTH_CALLBACK: '/bgm-oauth-callback',
  TRAKT_OAUTH_CALLBACK: '/trakt-oauth-callback',
  BATCH_MANAGE: '/library/batch-manage',
  SUBSCRIPTIONS: '/library/subscriptions',
}
