"""
参数配置 Schema 定义

配置项类型:
- string: 普通文本输入
- password: 密码输入（带遮罩）
- number: 数字输入
- boolean: 开关
- textarea: 多行文本
- select: 下拉选择

特殊字段:
- verifyEndpoint: 验证接口路径（如 Token 验证）
- suffix: 输入框后缀（如 "秒"）
- min/max: 数字输入的范围限制
- options: select 类型的选项列表
- placeholder: 输入框占位符
- description: 配置项描述
- rows: textarea 的行数
"""

CONFIG_SCHEMA = [
    {
        "key": "appearance",
        "label": "外观设置",
        "label_en": "Appearance",
        "label_tw": "外觀設定",
        "items": [
            {
                "key": "wallpaperAcgUrl",
                "label": "二次元壁纸图源",
                "label_en": "ACG Wallpaper URL",
                "label_tw": "二次元壁紙圖源",
                "type": "string",
                "description": "「二次元壁纸」页面样式的背景图地址。留空时仅显示本地渐变兜底，不向外部发起任何请求。可替换为其他随机图源，如 https://www.dmoe.cc/random.php 等。",
                "description_en": "Background image URL for the 'ACG Wallpaper' page style. Leave empty to show only a local gradient fallback. You can replace it with other random image sources.",
                "description_tw": "「二次元壁紙」頁面樣式的背景圖地址。留空時僅顯示本地漸層兜底，不向外部發起任何請求。可替換為其他隨機圖源。",
                "placeholder": "https://www.loliapi.com/acg/pc/",
            },
        ],
    },
    {
        "key": "security",
        "label": "安全设置",
        "label_en": "Security",
        "label_tw": "安全設定",
        "items": [
            {
                "key": "github_token",
                "label": "GitHub Token",
                "type": "password",
                "description": "用于请求 GitHub API，避免速率限制。无需任何权限，只需创建一个 Token 即可。",
                "description_en": "Used for GitHub API requests to avoid rate limits. No permissions required, just create a Token.",
                "description_tw": "用於請求 GitHub API，避免速率限制。無需任何權限，只需建立一個 Token 即可。",
                "placeholder": "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "verifyEndpoint": "/api/ui/config/github-token/verify",
            },
            {
                "key": "ipWhitelist",
                "label": "访问IP白名单",
                "label_en": "IP Whitelist",
                "label_tw": "存取IP白名單",
                "type": "textarea",
                "rows": 3,
                "description": "⚠️ 安全警告：白名单内的IP访问管理界面时无需登录！请谨慎配置。多个IP或CIDR网段请用英文逗号(,)分隔。留空表示禁用此功能。",
                "description_en": "⚠️ Security warning: IPs in the whitelist can access the admin panel without login! Configure carefully. Separate multiple IPs or CIDR ranges with commas (,). Leave empty to disable.",
                "description_tw": "⚠️ 安全警告：白名單內的IP存取管理介面時無需登入！請謹慎配置。多個IP或CIDR網段請用英文逗號(,)分隔。留空表示停用此功能。",
                "placeholder": "例如: 192.168.1.100, 10.0.0.0/8",
                "placeholder_en": "e.g.: 192.168.1.100, 10.0.0.0/8",
                "placeholder_tw": "例如: 192.168.1.100, 10.0.0.0/8",
            },
            {
                "key": "trustedProxies",
                "label": "受信任的反向代理",
                "label_en": "Trusted Reverse Proxies",
                "label_tw": "受信任的反向代理",
                "type": "textarea",
                "rows": 3,
                "description": "当请求来自这些IP时，将从 X-Forwarded-For 或 X-Real-IP 头中解析真实客户端IP。多个IP或CIDR网段请用英文逗号(,)分隔。",
                "description_en": "When requests come from these IPs, the real client IP will be parsed from X-Forwarded-For or X-Real-IP headers. Separate multiple IPs or CIDR ranges with commas (,).",
                "description_tw": "當請求來自這些IP時，將從 X-Forwarded-For 或 X-Real-IP 標頭中解析真實用戶端IP。多個IP或CIDR網段請用英文逗號(,)分隔。",
                "placeholder": "例如: 127.0.0.1, 192.168.1.0/24, 10.0.0.1/32",
                "placeholder_en": "e.g.: 127.0.0.1, 192.168.1.0/24, 10.0.0.1/32",
                "placeholder_tw": "例如: 127.0.0.1, 192.168.1.0/24, 10.0.0.1/32",
            },
            {
                "key": "jwtExpireMinutes",
                "label": "登录令牌有效期",
                "label_en": "Login Token Expiry",
                "label_tw": "登入令牌有效期",
                "type": "number",
                "suffix": "分钟",
                "suffix_en": "min",
                "suffix_tw": "分鐘",
                "min": 1,
                "max": 43200,
                "description": "JWT 令牌有效期（分钟），最长 30 天。修改后需要重新登录生效。",
                "description_en": "JWT token expiry in minutes, up to 30 days. Re-login required after change.",
                "description_tw": "JWT 令牌有效期（分鐘），最長 30 天。修改後需要重新登入生效。",
                "placeholder": "4320",
            },
        ],
    },
    {
        "key": "cache",
        "label": "缓存设置",
        "label_en": "Cache",
        "label_tw": "快取設定",
        "items": [
            {
                "key": "searchTtlSeconds",
                "label": "搜索缓存时间",
                "label_en": "Search Cache TTL",
                "label_tw": "搜尋快取時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": 10800,
                "description": "搜索结果的缓存时间，最低3小时（10800秒）",
                "description_en": "Cache time for search results, minimum 3 hours (10800 seconds)",
                "description_tw": "搜尋結果的快取時間，最低3小時（10800秒）",
                "placeholder": "10800",
            },
            {
                "key": "episodesTtlSeconds",
                "label": "分集缓存时间",
                "label_en": "Episode Cache TTL",
                "label_tw": "分集快取時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": 10800,
                "description": "分集列表的缓存时间，最低3小时（10800秒）",
                "description_en": "Cache time for episode lists, minimum 3 hours (10800 seconds)",
                "description_tw": "分集清單的快取時間，最低3小時（10800秒）",
                "placeholder": "10800",
            },
            {
                "key": "baseInfoTtlSeconds",
                "label": "基础信息缓存时间",
                "label_en": "Base Info Cache TTL",
                "label_tw": "基礎資訊快取時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": 10800,
                "description": "基础媒体信息的缓存时间，最低3小时（10800秒）",
                "description_en": "Cache time for basic media info, minimum 3 hours (10800 seconds)",
                "description_tw": "基礎媒體資訊的快取時間，最低3小時（10800秒）",
                "placeholder": "10800",
            },
            {
                "key": "metadataSearchTtlSeconds",
                "label": "元数据搜索缓存时间",
                "label_en": "Metadata Search Cache TTL",
                "label_tw": "中繼資料搜尋快取時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": 10800,
                "description": "元数据（如TMDB, Bangumi）搜索结果的缓存时间，最低3小时（10800秒）",
                "description_en": "Cache time for metadata (e.g. TMDB, Bangumi) search results, minimum 3 hours (10800 seconds)",
                "description_tw": "中繼資料（如TMDB, Bangumi）搜尋結果的快取時間，最低3小時（10800秒）",
                "placeholder": "10800",
            },
        ],
    },
    {
        "key": "performance",
        "label": "性能设置",
        "label_en": "Performance",
        "label_tw": "效能設定",
        "items": [
            {
                "key": "searchMaxResultsPerSource",
                "label": "每源最大搜索结果数",
                "label_en": "Max Results Per Source",
                "label_tw": "每源最大搜尋結果數",
                "type": "number",
                "min": 1,
                "max": 100,
                "description": "每个搜索源最多返回的结果数量。设置较小的值可以提高搜索速度。",
                "description_en": "Maximum number of results returned per search source. Smaller values improve search speed.",
                "description_tw": "每個搜尋源最多傳回的結果數量。設定較小的值可以提高搜尋速度。",
                "placeholder": "30",
            },
            {
                "key": "searchFallbackTimeout",
                "label": "后备搜索超时时间",
                "label_en": "Fallback Search Timeout",
                "label_tw": "後備搜尋逾時時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": -1,
                "max": 120,
                "description": "后备搜索接口等待结果的最大时间。设为 -1 表示无限等待直到出结果。超时后返回空结果，搜索任务继续在后台运行。",
                "description_en": "Max time to wait for fallback search results. -1 means wait indefinitely. Returns empty on timeout, search continues in background.",
                "description_tw": "後備搜尋介面等待結果的最大時間。設為 -1 表示無限等待直到出結果。逾時後傳回空結果，搜尋任務繼續在背景執行。",
                "placeholder": "30",
            },
            {
                "key": "matchFallbackTimeout",
                "label": "后备匹配超时时间",
                "label_en": "Fallback Match Timeout",
                "label_tw": "後備匹配逾時時間",
                "type": "number",
                "suffix": "秒",
                "suffix_en": "sec",
                "suffix_tw": "秒",
                "min": -1,
                "max": 300,
                "description": "后备匹配接口（/match）等待结果的最大时间。设为 -1 表示无限等待直到匹配完成。超时后返回未匹配，匹配任务继续在后台运行。",
                "description_en": "Max time to wait for fallback match (/match) results. -1 means wait indefinitely. Returns unmatched on timeout, match task continues in background.",
                "description_tw": "後備匹配介面（/match）等待結果的最大時間。設為 -1 表示無限等待直到匹配完成。逾時後傳回未匹配，匹配任務繼續在背景執行。",
                "placeholder": "60",
            },
            {
                "key": "fallbackSearchPosterCollage",
                "label": "后备搜索完成推送聚合海报",
                "label_en": "Fallback Search Poster Collage in Notification",
                "label_tw": "後備搜尋完成推播聚合海報",
                "type": "boolean",
                "description": "开启后，后备搜索完成的通知推送会把各结果海报聚合成一张带序号的九宫格图一并发出（仅 Telegram 等支持图片的渠道生效，聚合失败时自动降级为纯文字，不影响推送）。",
                "description_en": "When enabled, the fallback-search completion notification attaches a numbered poster collage of the results (only on image-capable channels like Telegram; silently falls back to text if collage fails).",
                "description_tw": "開啟後，後備搜尋完成的通知推播會把各結果海報聚合成一張帶序號的九宮格圖一併發出（僅 Telegram 等支援圖片的渠道生效，聚合失敗時自動降級為純文字，不影響推播）。",
            },
        ],
    },
    {
        "key": "database",
        "label": "数据库",
        "label_en": "Database",
        "label_tw": "資料庫",
        "items": [
            {
                "key": "mysqlBinlogRetentionDays",
                "label": "MySQL Binlog 保留天数",
                "label_en": "MySQL Binlog Retention Days",
                "label_tw": "MySQL Binlog 保留天數",
                "type": "number",
                "min": 0,
                "description": "（仅MySQL）自动清理多少天前的二进制日志（binlog）。0为不清理。需要SUPER或BINLOG_ADMIN权限。",
                "description_en": "(MySQL only) Auto-clean binary logs older than this many days. 0 to disable. Requires SUPER or BINLOG_ADMIN privileges.",
                "description_tw": "（僅MySQL）自動清理多少天前的二進位日誌（binlog）。0為不清理。需要SUPER或BINLOG_ADMIN權限。",
                "placeholder": "3",
            },
            {
                "key": "backupPath",
                "label": "备份存储路径",
                "label_en": "Backup Storage Path",
                "label_tw": "備份儲存路徑",
                "type": "text",
                "description": "数据库备份文件的存储目录。Docker 环境建议使用默认路径。",
                "description_en": "Storage directory for database backup files. Docker environments should use the default path.",
                "description_tw": "資料庫備份檔案的儲存目錄。Docker 環境建議使用預設路徑。",
                "placeholder": "/app/config/sql_backup",
            },
            {
                "key": "backupRetentionCount",
                "label": "备份保留数量",
                "label_en": "Backup Retention Count",
                "label_tw": "備份保留數量",
                "type": "number",
                "min": 1,
                "max": 100,
                "description": "保留最近多少个备份文件，超出的旧备份将被自动删除。",
                "description_en": "Number of recent backups to keep. Older backups beyond this count are auto-deleted.",
                "description_tw": "保留最近多少個備份檔案，超出的舊備份將被自動刪除。",
                "placeholder": "5",
            },
        ],
        "customComponent": "DatabaseBackupManager",
    },
    {
        "key": "scraper_update",
        "label": "弹幕源自动更新",
        "label_en": "Scraper Auto-Update",
        "label_tw": "彈幕源自動更新",
        "items": [
            {
                "key": "scraperAutoUpdateInterval",
                "label": "检查间隔",
                "label_en": "Check Interval",
                "label_tw": "檢查間隔",
                "type": "number",
                "suffix": "分钟",
                "suffix_en": "min",
                "suffix_tw": "分鐘",
                "min": 15,
                "max": 1440,
                "description": "自动检查更新的时间间隔，最低15分钟，最高1440分钟（24小时）。修改后需要重启服务生效。",
                "description_en": "Auto-check update interval, min 15 min, max 1440 min (24h). Restart required after change.",
                "description_tw": "自動檢查更新的時間間隔，最低15分鐘，最高1440分鐘（24小時）。修改後需要重啟服務生效。",
                "placeholder": "30",
            },
        ],
    },
    {
        "key": "ui",
        "label": "界面设置",
        "label_en": "UI Settings",
        "label_tw": "介面設定",
        "items": [
            {
                "key": "pageSizeLibrary",
                "label": "弹幕库列表 - 分页数量",
                "label_en": "Library List - Page Size",
                "label_tw": "彈幕庫列表 - 分頁數量",
                "type": "select",
                "options": [
                    {"value": "20", "label": "20 条/页", "label_en": "20/page", "label_tw": "20 條/頁"},
                    {"value": "50", "label": "50 条/页", "label_en": "50/page", "label_tw": "50 條/頁"},
                    {"value": "100", "label": "100 条/页", "label_en": "100/page", "label_tw": "100 條/頁"},
                    {"value": "200", "label": "200 条/页", "label_en": "200/page", "label_tw": "200 條/頁"},
                ],
                "description": "弹幕库页面的每页显示数量。修改后刷新页面生效。",
                "description_en": "Items per page in the library list. Refresh page after change.",
                "description_tw": "彈幕庫頁面的每頁顯示數量。修改後重新整理頁面生效。",
                "placeholder": "50",
            },
            {
                "key": "pageSizeEpisode",
                "label": "剧集列表 - 分页数量",
                "label_en": "Episode List - Page Size",
                "label_tw": "劇集列表 - 分頁數量",
                "type": "select",
                "options": [
                    {"value": "20", "label": "20 条/页", "label_en": "20/page", "label_tw": "20 條/頁"},
                    {"value": "50", "label": "50 条/页", "label_en": "50/page", "label_tw": "50 條/頁"},
                    {"value": "100", "label": "100 条/页", "label_en": "100/page", "label_tw": "100 條/頁"},
                    {"value": "200", "label": "200 条/页", "label_en": "200/page", "label_tw": "200 條/頁"},
                ],
                "description": "剧集详情页面的每页显示数量。修改后刷新页面生效。",
                "description_en": "Items per page in the episode detail page. Refresh page after change.",
                "description_tw": "劇集詳情頁面的每頁顯示數量。修改後重新整理頁面生效。",
                "placeholder": "50",
            },
            {
                "key": "pageSizeLocalItems",
                "label": "本地媒体列表 - 分页数量",
                "label_en": "Local Media List - Page Size",
                "label_tw": "本地媒體列表 - 分頁數量",
                "type": "select",
                "options": [
                    {"value": "20", "label": "20 条/页", "label_en": "20/page", "label_tw": "20 條/頁"},
                    {"value": "50", "label": "50 条/页", "label_en": "50/page", "label_tw": "50 條/頁"},
                    {"value": "100", "label": "100 条/页", "label_en": "100/page", "label_tw": "100 條/頁"},
                    {"value": "200", "label": "200 条/页", "label_en": "200/page", "label_tw": "200 條/頁"},
                ],
                "description": "本地媒体列表的每页显示数量。修改后刷新页面生效。",
                "description_en": "Items per page in the local media list. Refresh page after change.",
                "description_tw": "本地媒體列表的每頁顯示數量。修改後重新整理頁面生效。",
                "placeholder": "50",
            },
            {
                "key": "pageSizeMediaItems",
                "label": "媒体服务器列表 - 分页数量",
                "label_en": "Media Server List - Page Size",
                "label_tw": "媒體伺服器列表 - 分頁數量",
                "type": "select",
                "options": [
                    {"value": "20", "label": "20 条/页", "label_en": "20/page", "label_tw": "20 條/頁"},
                    {"value": "50", "label": "50 条/页", "label_en": "50/page", "label_tw": "50 條/頁"},
                    {"value": "100", "label": "100 条/页", "label_en": "100/page", "label_tw": "100 條/頁"},
                    {"value": "200", "label": "200 条/页", "label_en": "200/page", "label_tw": "200 條/頁"},
                ],
                "description": "媒体服务器作品列表的每页显示数量。修改后刷新页面生效。",
                "description_en": "Items per page in the media server list. Refresh page after change.",
                "description_tw": "媒體伺服器作品列表的每頁顯示數量。修改後重新整理頁面生效。",
                "placeholder": "100",
            },
            {
                "key": "pageSizeRefreshModal",
                "label": "追更管理列表 - 分页数量",
                "label_en": "Tracking List - Page Size",
                "label_tw": "追更管理列表 - 分頁數量",
                "type": "select",
                "options": [
                    {"value": "20", "label": "20 条/页", "label_en": "20/page", "label_tw": "20 條/頁"},
                    {"value": "50", "label": "50 条/页", "label_en": "50/page", "label_tw": "50 條/頁"},
                    {"value": "100", "label": "100 条/页", "label_en": "100/page", "label_tw": "100 條/頁"},
                    {"value": "200", "label": "200 条/页", "label_en": "200/page", "label_tw": "200 條/頁"},
                ],
                "description": "追更与标记管理弹窗的每页显示数量。修改后刷新页面生效。",
                "description_en": "Items per page in the tracking management modal. Refresh page after change.",
                "description_tw": "追更與標記管理彈窗的每頁顯示數量。修改後重新整理頁面生效。",
                "placeholder": "20",
            },
        ],
    },
    {
        "key": "name_conversion",
        "label": "名称转换",
        "label_en": "Name Conversion",
        "label_tw": "名稱轉換",
        "items": [
            {
                "key": "nameConversionEnabled",
                "label": "启用名称转换",
                "label_en": "Enable Name Conversion",
                "label_tw": "啟用名稱轉換",
                "type": "boolean",
                "description": "搜索时自动将非中文名称转换为中文，提高在中文弹幕源中的搜索准确率。元数据源都失败时，若启用了AI名称转换则使用AI兜底。",
                "description_en": "Auto-convert non-Chinese names to Chinese during search to improve accuracy in Chinese danmaku sources. Falls back to AI name conversion when all metadata sources fail.",
                "description_tw": "搜尋時自動將非中文名稱轉換為中文，提高在中文彈幕源中的搜尋準確率。中繼資料來源都失敗時，若啟用了AI名稱轉換則使用AI兜底。",
            },
            {
                "key": "nameConversionT2SEnabled",
                "label": "繁体自动转简体",
                "label_en": "Auto Traditional to Simplified",
                "label_tw": "繁體自動轉簡體",
                "type": "boolean",
                "description": "搜索时自动将繁体中文标题转换为简体，提高在简体弹幕源中的搜索匹配率。此选项独立于上方的名称转换开关。",
                "description_en": "Auto-convert Traditional Chinese titles to Simplified during search to improve matching in Simplified Chinese danmaku sources. Independent of the name conversion toggle above.",
                "description_tw": "搜尋時自動將繁體中文標題轉換為簡體，提高在簡體彈幕源中的搜尋比對率。此選項獨立於上方的名稱轉換開關。",
            },
        ],
        "customComponent": {
            "type": "SortablePriorityList",
            "props": {
                "configKey": "nameConversionSourcePriority",
                "title": "元数据源查询优先级",
                "title_en": "Metadata Source Priority",
                "title_tw": "中繼資料來源查詢優先級",
                "titleIcon": "🔢",
                "description": "名称转换时会并行查询所有启用的元数据源，按优先级顺序返回第一个有结果的中文名称。",
                "description_en": "During name conversion, all enabled metadata sources are queried in parallel. The first Chinese name found by priority order is returned.",
                "description_tw": "名稱轉換時會並行查詢所有啟用的中繼資料來源，按優先級順序傳回第一個有結果的中文名稱。",
                "availableItems": [
                    {"key": "bangumi", "name": "Bangumi", "description": "动漫数据库，中文名称准确", "description_en": "Anime database, accurate Chinese names", "description_tw": "動漫資料庫，中文名稱準確"},
                    {"key": "tmdb", "name": "TMDB", "description": "影视数据库，覆盖范围广", "description_en": "Movie & TV database, wide coverage", "description_tw": "影視資料庫，覆蓋範圍廣"},
                    {"key": "tvdb", "name": "TVDB", "description": "电视剧数据库", "description_en": "TV series database", "description_tw": "電視劇資料庫"},
                    {"key": "douban", "name": "Douban", "description": "豆瓣，国产剧/电影中文名称准确", "description_en": "Douban, accurate Chinese names for Chinese dramas/movies", "description_tw": "豆瓣，國產劇/電影中文名稱準確"},
                    {"key": "imdb", "name": "IMDB", "description": "国际电影数据库", "description_en": "International movie database", "description_tw": "國際電影資料庫"},
                ],
                "tips": [
                    "拖拽调整优先级顺序，排在前面的源优先使用",
                    "关闭开关可禁用该源的查询",
                    "Bangumi 对动漫的中文名称更准确",
                    "Douban 对国产剧/电影的中文名称更准确",
                    "TMDB 覆盖范围更广，包含电影和电视剧",
                    "元数据源都失败时，若启用了AI名称转换则使用AI兜底",
                ],
                "tips_en": [
                    "Drag to adjust priority order, sources at the top are used first",
                    "Toggle off to disable a source",
                    "Bangumi has more accurate Chinese names for anime",
                    "Douban has more accurate Chinese names for Chinese dramas/movies",
                    "TMDB has wider coverage including movies and TV series",
                    "Falls back to AI name conversion when all metadata sources fail",
                ],
                "tips_tw": [
                    "拖曳調整優先級順序，排在前面的來源優先使用",
                    "關閉開關可停用該來源的查詢",
                    "Bangumi 對動漫的中文名稱更準確",
                    "Douban 對國產劇/電影的中文名稱更準確",
                    "TMDB 覆蓋範圍更廣，包含電影和電視劇",
                    "中繼資料來源都失敗時，若啟用了AI名稱轉換則使用AI兜底",
                ],
                "showSwitch": True,
            },
        },
    },
]


def get_config_schema():
    """获取配置 Schema"""
    return CONFIG_SCHEMA

